CREATE SCHEMA NPT;

create table NPT.TNPCOX
(
    ORDERNR    CHAR(7)   not null,
    PRODART    CHAR(1)   not null,
    RESTID     CHAR(8)   not null,
    RESP_SYS   CHAR(8)   not null default '',
    REST_STAT  CHAR(1)   not null default '',
    REJ_REASON CHAR(2)   not null default '',
    DIST_REST  CHAR(1),
    INV_REST   CHAR(1),
    CARDO_REST CHAR(1),
    WEST_REST  CHAR(1),
    AENDTIME   TIMESTAMP not null default current_timestamp,
    AENDUSER   CHAR(8)   not null default '',
    ISRTIME    TIMESTAMP not null default current_timestamp,
    PRIMARY KEY (ORDERNR, PRODART, RESTID)
);

COMMENT
on TABLE NPT.TNPCOX IS 'FAHRZEUGORDERSPERRUNG';


CREATE TABLE
    NPT.TNPPAB
(
    ABLAUFNR        CHAR(2)       NOT NULL,
    ABLAUFBE        CHAR(30)      NOT NULL DEFAULT '',
    AENDUSPR        CHAR(2),
    AENDUSNR        CHAR(6),
    AENDTIME        TIMESTAMP     NOT NULL DEFAULT current_timestamp,
    BEZUGSWK        CHAR(2)       NOT NULL DEFAULT '',
    BEZUGSOE        CHAR(2)       NOT NULL DEFAULT '',
    BEZSTUFE        CHAR(1)       NOT NULL DEFAULT '',
    MELDESCHW_OBEN  DECIMAL(5, 2) NOT NULL DEFAULT 0,
    MELDESCHW_UNTEN DECIMAL(5, 2) NOT NULL DEFAULT 0,
    L_ABGESCHL_TAG  DATE          NOT NULL DEFAULT current_date,
    PAK_PRIO        CHAR(1)       NOT NULL DEFAULT '',
    PAK_GEWICHT     SMALLINT      NOT NULL DEFAULT 0,
    SICHZMOT        SMALLINT,
    SICHZKAR        SMALLINT,
    ST5000OK        CHAR(1)       NOT NULL DEFAULT '',
    STZ5000         TIMESTAMP,
    EPLD5000        DATE,
    EPLDEPPZ        DATE,
    BEZSTAT         CHAR(4)       NOT NULL DEFAULT '',
    IVSRELEV        CHAR(1)       NOT NULL DEFAULT '',
    ZUEBAB          TIMESTAMP,
    ZMAEINP         TIMESTAMP,
    ZOPCORE         TIMESTAMP,
    PRODART         CHAR(1)       NOT NULL DEFAULT '1',
    KZF2TERM        CHAR(1),
    BWPRMAX         SMALLINT,
    KZ_AKTIV        CHAR(1)       NOT NULL DEFAULT '',
    PRIMARY KEY (ABLAUFNR)
);

COMMENT
ON TABLE NPT.TNPPAB  IS 'FABLAUF';

CREATE TABLE NPT.TNPPAF
(
    ABLAUFNR   CHAR(2)   NOT NULL,
    FBST       CHAR(2)   NOT NULL,
    FBNR       CHAR(2)   NOT NULL,
    FBWK       CHAR(2)   NOT NULL,
    VERBRSTA   CHAR(4),
    AENDUSPR   CHAR(2),
    AENDUSNR   CHAR(6),
    AENDTIME   TIMESTAMP NOT NULL default current_timestamp,
    RESTAUF    CHAR(1)   NOT NULL DEFAULT '',
    KAM_FAKTOR DECIMAL(4, 2),
    ROVORLSV   CHAR(2)   NOT NULL DEFAULT '',
    GES_FBST   CHAR(2),
    GES_FBNR   CHAR(2),
    GES_FBWK   CHAR(2),
    PRIMARY KEY (ABLAUFNR, FBST, FBNR, FBWK)
);

COMMENT
ON TABLE NPT.TNPPAF IS 'FABFBER' ;


CREATE TABLE NPT.TNPPAT
(
    ABLAUFNR  CHAR(2)   NOT NULL,
    TYP       CHAR(4)   NOT NULL,
    AENDUSPR  CHAR(2),
    AENDUSNR  CHAR(6),
    AENDTIME  TIMESTAMP NOT NULL default current_timestamp,
    LQANOTAG  DATE,
    VERB_PRIO CHAR(1)   NOT NULL DEFAULT '',
    PRIMARY KEY (ABLAUFNR, TYP)
);

COMMENT
ON TABLE NPT.TNPPAT IS 'FABSTYP';


CREATE TABLE NPT.TNPPFG
(
    ORDERNR    CHAR(7)    NOT NULL,
    PRODART    CHAR(1)    NOT NULL,
    AUSSTATT   CHAR(2),
    FARBAUS    CHAR(2),
    WOPAWOCH   CHAR(8),
    FZGF2HO    DATE,
    FZSTAKT    CHAR(4),
    FZSTAKTD   DATE,
    FZSTAKTZ   TIME,
    FZAEND     SMALLINT   NOT NULL DEFAULT 0,
    PRIO       CHAR(1)    NOT NULL DEFAULT '',
    KUNDENNR   DECIMAL(5),
    VERSART    CHAR(2)    NOT NULL DEFAULT '',
    BEHKDNR    CHAR(5),
    SWKUNART   CHAR(1),
    SWKZ       CHAR(1)    NOT NULL DEFAULT '',
    SWPW       CHAR(8)    NOT NULL DEFAULT '',
    SWANSPNR   CHAR(6),
    SWANSPPR   CHAR(2),
    KEZVERW    CHAR(1)    NOT NULL DEFAULT '',
    FZGF2KOR   DATE,
    FGNRWOCH   CHAR(8),
    PWKUNDE    CHAR(8)    NOT NULL DEFAULT '',
    LWKUNDE    CHAR(8)    NOT NULL DEFAULT '',
    VERTPRIO   CHAR(1)    NOT NULL DEFAULT '',
    UMTERMIN   DECIMAL(2) NOT null DEFAULT 0,
    PRIOTIME   TIMESTAMP,
    PAKNR      CHAR(5),
    HAFENKEZ   CHAR(3)    NOT NULL DEFAULT '',
    KUNDART    CHAR(1)    NOT NULL DEFAULT '',
    ORDERART   CHAR(1)    NOT NULL DEFAULT '',
    ORDERDAT   DATE,
    MODJAHR    CHAR(1)    NOT NULL DEFAULT '',
    F2WOCHE    CHAR(8)    NOT NULL DEFAULT '',
    PWVGSO     CHAR(8)    NOT NULL DEFAULT '',
    DISTRIKT   CHAR(2)    NOT NULL DEFAULT '',
    LAENDKZ    CHAR(3)    NOT NULL DEFAULT '',
    KDMERKSV   CHAR(2),
    SVKUNDNR   CHAR(6),
    POLSTER    CHAR(4),
    AENDTIME   TIMESTAMP  NOT NULL default current_timestamp,
    KZINEX     CHAR(1)    NOT NULL DEFAULT '',
    ZPKTAKT    CHAR(8),
    STOZPKT    CHAR(2),
    F2TERMA    CHAR(1)    NOT NULL DEFAULT '',
    F2LFDNR    CHAR(5)    NOT NULL DEFAULT '',
    HDLQUOTE   CHAR(1)    NOT NULL DEFAULT '',
    BUCHWOCH   CHAR(8)    NOT NULL DEFAULT '',
    KZ5000     CHAR(1)    NOT NULL DEFAULT '',
    F2ST11     DATE,
    F2SPERR    CHAR(1)    NOT NULL DEFAULT '',
    KEZST12M   CHAR(1)    NOT NULL DEFAULT '',
    AZPKT      CHAR(8),
    AZPKTSTO   CHAR(2),
    FILTKZ     CHAR(1)    NOT NULL DEFAULT '',
    AENDSPER   CHAR(1)    NOT NULL DEFAULT '',
    STDNR      CHAR(5),
    ZIELWOCH   CHAR(8)    NOT NULL DEFAULT '',
    ZULF2TAG   DATE,
    ZULF2MAN   CHAR(1)    NOT NULL DEFAULT '',
    KZPOLSPA   CHAR(1)    NOT NULL DEFAULT '',
    POLSPA     CHAR(3),
    ZIELIVS    CHAR(5)    NOT NULL DEFAULT '',
    AUSSTATW   CHAR(2),
    FARBAUSW   CHAR(2),
    KZPOLSPW   CHAR(1)    NOT NULL DEFAULT '',
    POLSPW     CHAR(3),
    VERBPOLS   CHAR(1)    NOT NULL DEFAULT '',
    KUNDAKT    CHAR(5),
    PAKNRAKT   CHAR(5),
    HAFENAKT   CHAR(3)    NOT NULL DEFAULT '',
    LAENDAKT   CHAR(3)    NOT NULL DEFAULT '',
    DISTRAKT   CHAR(2)    NOT NULL DEFAULT '',
    VERSAKT    CHAR(2)    NOT NULL DEFAULT '',
    F2IST      DATE,
    ENDKCAT    CHAR(2),
    ENDK       CHAR(6),
    EHDLCAT    CHAR(2),
    EHDL       CHAR(6),
    GHDLCAT    CHAR(2),
    GHDL       CHAR(6),
    DELOCCAT   CHAR(2),
    DELOC      CHAR(6),
    SYSDELOC   CHAR(1)    NOT NULL DEFAULT '',
    DESDELIV   DATE,
    KOVP_KEZ   CHAR(1)    NOT NULL DEFAULT '',
    RELDAT     DATE,
    SERVICE1   CHAR(1)    NOT NULL DEFAULT '',
    SERVICE2   CHAR(1)    NOT NULL DEFAULT '',
    SERVICE3   CHAR(1)    NOT NULL DEFAULT '',
    SERVICE4   CHAR(1)    NOT NULL DEFAULT '',
    SERVICE5   CHAR(1)    NOT NULL DEFAULT '',
    SERVICE6   CHAR(1)    NOT NULL DEFAULT '',
    SELFTRST   CHAR(1)    NOT NULL DEFAULT '',
    NACHRUES   CHAR(1)    NOT NULL DEFAULT '',
    ORD_REQ    TIMESTAMP,
    DIST_ORD   CHAR(8),
    WEST_ORD   CHAR(8),
    F2ISTZ     TIME,
    VERSCHR    CHAR(1)    NOT NULL DEFAULT '',
    UNFALL     CHAR(1)    NOT NULL DEFAULT '',
    ENTWFZG    CHAR(1)    NOT NULL DEFAULT '',
    GEBRFZG    CHAR(1)    NOT NULL DEFAULT '',
    SWMUSTFZ   CHAR(1)    NOT NULL DEFAULT '',
    REAKTD     DATE,
    REAKTZ     TIME,
    CONS_ID    CHAR(7),
    LEASING    CHAR(1)    NOT NULL DEFAULT '',
    VERPACK    CHAR(3)    NOT NULL DEFAULT '',
    CONF_REQ   TIMESTAMP,
    DIRFAKT    CHAR(1)    NOT NULL DEFAULT '',
    POLOCCAT   CHAR(2),
    POLOC      CHAR(6),
    DISTPRIO   CHAR(1)    NOT NULL DEFAULT '',
    MFBT       CHAR(2),
    ZAHLWEIS   CHAR(1)    NOT NULL DEFAULT '',
    BANK       CHAR(1)    NOT NULL DEFAULT '',
    LEASSTOR   CHAR(1)    NOT NULL DEFAULT '',
    REWUNST    DATE,
    BESTELLT   DATE,
    BESTELLZ   CHAR(25)   NOT NULL DEFAULT '',
    SWMANDANT  CHAR(2),
    PREISSIM   CHAR(1)    NOT NULL DEFAULT '',
    TYPPREIS   DECIMAL(13, 2),
    SA_PREIS   DECIMAL(13, 2),
    GESPREIS   DECIMAL(13, 2),
    RECHDAT    DATE,
    RECHNR     CHAR(10),
    STLOCCAT   CHAR(2),
    STLOC      CHAR(6),
    REPORDNR   CHAR(7),
    REEMPCAT   CHAR(2),
    REEMP      CHAR(6),
    REICHW     CHAR(1)    NOT NULL DEFAULT '',
    WERKSTPF   CHAR(1)    NOT NULL DEFAULT '',
    AUSSTATU   CHAR(2),
    FARBAUSU   CHAR(2),
    KZPOLSPU   CHAR(1)    NOT NULL DEFAULT '',
    POLSPU     CHAR(3),
    SPEEDREL   CHAR(1)    NOT NULL DEFAULT '',
    IVSMODTS   TIMESTAMP,
    WARENEIN   CHAR(1)    NOT NULL DEFAULT '',
    STLOCTS    TIMESTAMP,
    SBART      CHAR(8)    NOT NULL DEFAULT '',
    ABNEHGR    CHAR(2),
    LADSCHIF   CHAR(7),
    LADLKW     CHAR(7),
    ANSPFIFF   CHAR(1)    NOT NULL DEFAULT '',
    EG_KZ      CHAR(1)    NOT NULL DEFAULT '',
    EG_LAND    CHAR(2)    NOT NULL DEFAULT '',
    KONDKCAT   CHAR(2),
    KONDK      CHAR(6),
    FAKRUECK   CHAR(1)    NOT NULL DEFAULT '',
    VERBRDEU   CHAR(1)    NOT NULL DEFAULT '',
    EXPAUSST   CHAR(1)    NOT NULL DEFAULT '',
    PFIFFMAN   CHAR(2),
    PRBART_T   CHAR(1),
    PRBKEN_T   CHAR(6),
    PRBART_A   CHAR(1),
    PRBKEN_A   CHAR(6),
    PREISGEN   DATE,
    WAEHRUNG   CHAR(3)    NOT NULL DEFAULT '',
    MWST       DECIMAL(7, 4),
    ZAHLZIEL   CHAR(3)    NOT NULL DEFAULT '',
    KURSFIX    DECIMAL(7, 4),
    KURSEXPO   DECIMAL(1),
    ZAHL_WEI   CHAR(2),
    UNTSCHR1   CHAR(2),
    UNTSCHR2   CHAR(2),
    RECHSPR    CHAR(2),
    ZEILENST   CHAR(1)    NOT NULL DEFAULT '',
    SEP_ZUBE   CHAR(1)    NOT NULL DEFAULT '',
    VKANR1     CHAR(2),
    VKANR2     CHAR(2),
    TRKS       CHAR(4),
    VALUTADA   DATE,
    DAT_KOND   DATE,
    UMSATZST   CHAR(13)   NOT NULL DEFAULT '',
    RETXENTF   CHAR(1)    NOT NULL DEFAULT '',
    RBDISPKZ   CHAR(1)    NOT NULL DEFAULT '',
    PROFORMA   CHAR(1),
    ABBETA     DATE,
    COL_CRIT   CHAR(1),
    FAKTBEG    DATE,
    F2LATEST   DATE,
    PDI_FLAG   CHAR(1),
    F2TAGTE    DATE,
    BWENTRYT   TIMESTAMP,
    KZBMWELT   CHAR(1)    NOT NULL DEFAULT '',
    STORNOKZ   CHAR(1),
    STKDCAT    CHAR(2),
    STKD       CHAR(6),
    VIPKUNDE   CHAR(1),
    TANKSTUF   CHAR(1),
    STANDZ     CHAR(1),
    PROZZ      CHAR(1),
    "security" CHAR(1),
    ABHOLFR    DATE,
    ABHOLSP    DATE,
    ABWUWO     CHAR(6),
    BWUEBEGT   TIMESTAMP,
    DELOC50    CHAR(6),
    DELOCC50   CHAR(2),
    ANLTAGAZ   DATE,
    ANLTAGWS   DATE,
    ABTAG      DATE,
    ABWKS      CHAR(6),
    ABWKSCAT   CHAR(2),
    WSVZDLZ    SMALLINT,
    WSVZTEIL   SMALLINT,
    DISTLATE   CHAR(1),
    TANKSTIS   CHAR(1),
    DISPOTAG   DATE,
    WSTEILBG   DATE,
    PRODMASN   CHAR(4),
    KD_GRP     CHAR(8),
    STVIP      CHAR(1),
    OENTRYD    DATE,
    OENTRYT    TIME,
    FZGF2KT    TIME,
    MSGQUEUE   CHAR(2),
    F2IDEAL    DATE,
    FAKT_LT    DATE,
    FAKTLATE   CHAR(1),
    GFZMODTS   TIMESTAMP,
    EXPLOCCA   CHAR(2),
    EXPLOC     CHAR(6),
    EXPDELWK   CHAR(6),
    EXPDELD    DATE,
    EXPDELT    TIME,
    KZSABI     CHAR(1)    NOT NULL DEFAULT '',
    VERWA_PO   CHAR(1)    NOT NULL DEFAULT '',
    VERWAPOW   CHAR(1)    NOT NULL DEFAULT '',
    VERWAPOU   CHAR(1)    NOT NULL DEFAULT '',
    SABSPDAT   DATE,
    TERMTREU   CHAR(1)    NOT NULL DEFAULT '',
    ANZ_REL    CHAR(1)    NOT NULL DEFAULT '',
    F2K_5055   DATE,
    F2KT5055   TIME,
    F2FRUEHD   DATE,
    F2FRUEHZ   TIME,
    F2SPAETD   DATE,
    F2SPAETZ   TIME,
    F2KABWST   DECIMAL(4),
    F2KABWMI   DECIMAL(2),
    F2IABWST   DECIMAL(4),
    F2IABWMI   DECIMAL(2),
    ORDART12   CHAR(1)    NOT NULL DEFAULT '',
    ORDART50   CHAR(1)    NOT NULL DEFAULT '',
    KEZANLM    CHAR(1)    NOT NULL DEFAULT '',
    TERMTROR   CHAR(1)    NOT NULL DEFAULT '',
    WOCHABW    DECIMAL(4),
    DLZA5053   DECIMAL(6, 2),
    DLZS5053   DECIMAL(8, 2),
    DLZA5060   DECIMAL(6, 2),
    DLZS5060   DECIMAL(8, 2),
    KZROBI     CHAR(1)    NOT NULL DEFAULT '',
    KZSPHORI   CHAR(1)    NOT NULL DEFAULT '',
    QUOTAMON   CHAR(6),
    ABBEZ      TIME,
    ABHOLT_T   DATE,
    ABHOLT_Z   TIME,
    ABHOLE_T   DATE,
    ABHOLE_Z   TIME,
    UEBERG_T   DATE,
    UEBERG_Z   TIME,
    BUTABHTE   DATE,
    BUZABHTE   TIME,
    RUECKB_T   DATE,
    RUECKB_Z   TIME,
    BUTRUE_T   DATE,
    BUTRUE_Z   TIME,
    RUECKV_T   DATE,
    RUECKI_T   DATE,
    RUECKI_Z   TIME,
    RGLOCCAT   CHAR(2),
    RGLOC      CHAR(6),
    RILOCCAT   CHAR(2),
    RILOC      CHAR(6),
    ZUL_FLAG   CHAR(1)    NOT NULL DEFAULT '',
    ZULSTS_T   DATE,
    ZULENS_T   DATE,
    ZULST_T    DATE,
    ZULEN_T    DATE,
    ZULLATE    CHAR(1)    NOT NULL DEFAULT '',
    ZUL_ORT    CHAR(6),
    ZULDATUM   DATE,
    ZULKENNZ   CHAR(12),
    FAKTE_LT   DATE,
    FAKTENDE   DATE,
    FAKZAHLE   CHAR(1)    NOT NULL DEFAULT '',
    ZAHLART    CHAR(1)    NOT NULL DEFAULT '',
    ANLZEIWS   TIME,
    ANLTWSHO   DATE,
    ANLZWSHO   TIME,
    ANLZEIAZ   TIME,
    WR_FLAG    CHAR(1)    NOT NULL DEFAULT '',
    VMS_ORD    CHAR(12),
    WESTLATE   CHAR(1)    NOT NULL DEFAULT '',
    ENDKUNDE   CHAR(10),
    SVW_KAT    CHAR(3),
    SVW_BENR   CHAR(10),
    WHBT       CHAR(2),
    ZWNUTZCA   CHAR(2),
    ZWNUTZ     CHAR(6),
    ZWFP_KAT   CHAR(3),
    ZWZUL_T    DATE,
    COMPL_TS   TIMESTAMP,
    GTSREPTS   TIMESTAMP,
    GTSREPLY   CHAR(1)    NOT NULL DEFAULT '',
    ABHOLTFR   DATE,
    AREEMPCA   CHAR(2),
    AREEMP     CHAR(6),
    TERMROLL   CHAR(1)    NOT NULL DEFAULT '',
    ABHOLMAN   CHAR(1)    NOT NULL DEFAULT '',
    PODEPCAT   CHAR(2),
    PODEP      CHAR(6),
    TERMROLR   CHAR(1)    NOT NULL DEFAULT '',
    ABHOLTMA   CHAR(1)    NOT NULL DEFAULT '',
    RUECKTMA   CHAR(1)    NOT NULL DEFAULT '',
    ABHOLSUP   CHAR(1)    NOT NULL DEFAULT '',
    RUECKSUP   CHAR(1)    NOT NULL DEFAULT '',
    FGNR7ABH   CHAR(7),
    FGNR7RUE   CHAR(7),
    ABZEIT     TIME,
    TERMARTA   CHAR(1)    NOT NULL DEFAULT '',
    TERMARTR   CHAR(1)    NOT NULL DEFAULT '',
    PDI_ERL    CHAR(1)    NOT NULL DEFAULT '',
    BUCHKZA    CHAR(1)    NOT NULL DEFAULT '',
    BUCHKZR    CHAR(1)    NOT NULL DEFAULT '',
    STDNRAKT   CHAR(5),
    AUSLORT    CHAR(10),
    LOTVEHID   CHAR(2),
    LOTNR      CHAR(9),
    PACKWOCH   CHAR(8),
    FIXPRODW   CHAR(1)    NOT NULL DEFAULT '',
    KNG_FLAG   CHAR(1)    NOT NULL DEFAULT '',
    SENDER     CHAR(8)    NOT NULL DEFAULT '',
    FGNR10ABH  CHAR(10),
    FGNR10RUE  CHAR(10),
    COUNTRY3   CHAR(3),
    SALESCH    CHAR(4),
    PRIMARY KEY (ORDERNR, PRODART)
);

COMMENT
ON TABLE NPT.TNPPFG IS 'FZGWKORD FZGORDER';


CREATE TABLE NPT.TNPPOA
(
    ORDERNR  CHAR(7)   NOT NULL,
    PRODART  CHAR(1)   NOT NULL,
    AENDTIME TIMESTAMP NOT NULL,
    AENDSTAT CHAR(4),
    TABNAME  CHAR(6)   NOT NULL DEFAULT '',
    SPALTNAM CHAR(8)   NOT NULL DEFAULT '',
    WERTALT  CHAR(26),
    WERTNEU  CHAR(26),
    AENDUSPR CHAR(2),
    AENDUSNR CHAR(6),
    RESTKEY  CHAR(10),
    RM_RELEV CHAR(1)   NOT NULL DEFAULT '',
    PART_KZ  CHAR(2)   NOT NULL DEFAULT '00',
    AENDPGM  CHAR(8),
    PRIMARY KEY (ORDERNR, PRODART, AENDTIME, PART_KZ)
)PARTITION BY RANGE (PART_KZ);

CREATE TABLE NPT.TNPPOA_PARTITION_1
 PARTITION OF NPT.TNPPOA FOR VALUES FROM (MINVALUE) TO ('04');
CREATE TABLE NPT.TNPPOA_PARTITION_2
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('04') TO ('08') ;
CREATE TABLE NPT.TNPPOA_PARTITION_3
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('08') TO ('12') ;
CREATE TABLE NPT.TNPPOA_PARTITION_4
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('12') TO ('16') ;
CREATE TABLE NPT.TNPPOA_PARTITION_5
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('16') TO ('20') ;
CREATE TABLE NPT.TNPPOA_PARTITION_6
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('20')TO ('24') ;
CREATE TABLE NPT.TNPPOA_PARTITION_7
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('24') TO ('28');
CREATE TABLE NPT.TNPPOA_PARTITION_8
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('28') TO ('32') ;
CREATE TABLE NPT.TNPPOA_PARTITION_9
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('32') TO ('36') ;
CREATE TABLE NPT.TNPPOA_PARTITION_10
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('36') TO ('40') ;
CREATE TABLE NPT.TNPPOA_PARTITION_11
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('40')TO ('44') ;
CREATE TABLE NPT.TNPPOA_PARTITION_12
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('44')TO ('48') ;
CREATE TABLE NPT.TNPPOA_PARTITION_13
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('48') TO ('52') ;
CREATE TABLE NPT.TNPPOA_PARTITION_14
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('52') TO ('56');
CREATE TABLE NPT.TNPPOA_PARTITION_15
 PARTITION OF NPT.TNPPOA FOR VALUES FROM('56') TO ('60') ;
CREATE TABLE NPT.TNPPOA_PARTITION_16
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('60') TO ('64') ;
CREATE TABLE NPT.TNPPOA_PARTITION_17
 PARTITION OF NPT.TNPPOA FOR VALUES FROM('64') TO ('68') ;
CREATE TABLE NPT.TNPPOA_PARTITION_18
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('68') TO ('72') ;
CREATE TABLE NPT.TNPPOA_PARTITION_19
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('72')TO ('76') ;
CREATE TABLE NPT.TNPPOA_PARTITION_20
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('76')TO ('80') ;
CREATE TABLE NPT.TNPPOA_PARTITION_21
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('80') TO ('84');
CREATE TABLE NPT.TNPPOA_PARTITION_22
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('84')TO ('88') ;
CREATE TABLE NPT.TNPPOA_PARTITION_23
 PARTITION OF NPT.TNPPOA FOR VALUES FROM ('88') TO ('92')   ;
CREATE TABLE NPT.TNPPOA_PARTITION_24
 PARTITION OF NPT.TNPPOA FOR VALUES FROM('92') TO ('96')   ;
CREATE TABLE NPT.TNPPOA_PARTITION_25
 PARTITION OF NPT.TNPPOA FOR VALUES FROM('96') TO (MAXVALUE) ;


CREATE TABLE NPT.TNPPOS
(
    ORDERNR  CHAR(7) NOT NULL,
    PRODART  CHAR(1) NOT NULL,
    PRIMANR  CHAR(3) NOT NULL,
    PRIMAHI  CHAR(1) NOT NULL DEFAULT '',
    KZSERIE  CHAR(1) NOT NULL DEFAULT '',
    KZPRIMPA CHAR(1) NOT NULL DEFAULT '',
    PRIMAPA  CHAR(3),
    KZVERBAU CHAR(1) NOT NULL DEFAULT '',
    WERKST   CHAR(1) NOT NULL DEFAULT '',
    VERWA_SA CHAR(1) NOT NULL DEFAULT '',
    FARB_ABH CHAR(1) NOT NULL DEFAULT '',
    LACK_L   CHAR(3),
    FARBAUSL CHAR(2),
    PRIMARY KEY (ORDERNR, PRODART, PRIMANR)
);

COMMENT
ON TABLE NPT.TNPPOS IS 'ORDSALP';

CREATE TABLE NPT.TNPPP3
(
    PRODWOCH   CHAR(8) NOT NULL,
    VON_DAT    DATE    NOT NULL,
    BIS_DAT    DATE    NOT NULL,
    BEDARF_BIS DATE,
    PRIMARY KEY (PRODWOCH)
);

COMMENT
ON TABLE NPT.TNPPP3 IS 'PRODWOCHEN_INTERVALLE' ;

CREATE TABLE NPT.TNPPOR
(
    ORDERNR   CHAR(7)   NOT NULL,
    PRODART   CHAR(1)   NOT NULL,
    PRODGRUP  CHAR(2)   NOT NULL,
    TYP       CHAR(4)   NOT NULL,
    KZFZGST   CHAR(1)   NOT NULL DEFAULT '',
    LACK      CHAR(3),
    ORFBSTEB  CHAR(2),
    ORFBNREB  CHAR(2),
    ORFBWKEB  CHAR(2),
    ORDGUELT  DATE,
    FZGSTNR   CHAR(4)   NOT NULL DEFAULT '',
    KEZSPERR  CHAR(1)   NOT NULL DEFAULT '',
    STDFRUEH  DATE,
    ORDFRUEH  DATE,
    STDSPAET  DATE,
    ORDSPAET  DATE,
    AUFTRTXT  CHAR(79)  NOT NULL DEFAULT '',
    AENDTIME  TIMESTAMP NOT NULL default current_timestamp,
    TABAEND   TIMESTAMP,
    VERTSPER  CHAR(1)   NOT NULL DEFAULT '',
    KZFZMELD  CHAR(1)   NOT NULL DEFAULT '',
    LOESCHKZ  CHAR(1)   NOT NULL DEFAULT '',
    FZSTAND   TIMESTAMP,
    FZGSTGRP  CHAR(3)   NOT NULL DEFAULT '',
    KZLACKPA  CHAR(1)   NOT NULL DEFAULT '',
    LACKPA    CHAR(3),
    FZSPERRE  CHAR(1)   NOT NULL DEFAULT '',
    AENDTYP   TIMESTAMP,
    VGFRUEH   DATE,
    VGSPAET   DATE,
    KZLACKPW  CHAR(1)   NOT NULL DEFAULT '',
    LACKPW    CHAR(3),
    REAKTD    DATE,
    REAKTZ    TIME,
    KZLACKPU  CHAR(1)   NOT NULL DEFAULT '',
    LACKPU    CHAR(3),
    LACKW     CHAR(3),
    VERWA_LA  CHAR(1)   NOT NULL DEFAULT '',
    VERWALAW  CHAR(1)   NOT NULL DEFAULT '',
    VERWALAU  CHAR(1)   NOT NULL DEFAULT '',
    OA_SPERRE CHAR(1)   NOT NULL DEFAULT '',
    PIPEID    BIGINT    NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (START WITH 50000000 INCREMENT BY 1 MINVALUE 50000000 MAXVALUE 9223372036854775807),
    PRIMARY KEY (ORDERNR, PRODART)
);

COMMENT
ON TABLE NPT.TNPPOR IS 'ORDER'      ;
